name: Build and Test

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build JAR
        run: ./gradlew build

      - name: Upload Library Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Library Artifact
          path: |
            build/libs/*.jar
            app/build/outputs/aar/*.aar
